image: docker:latest

stages:
  - test
  - build
  - package

services:
  - name: cockroachdb/cockroach:v20.1.4
    entrypoint:
      - "bash"
    command:
      - -c
      - >
        /cockroach/cockroach start-single-node --insecure --store=type=mem,size=10% --listen-addr=0.0.0.0:26257 --background --http-addr=0.0.0.0:26258 --log-file-verbosity WARNING;
        /cockroach/cockroach sql --host 127.0.0.1:26257 --insecure -e 'set sql_safe_updates=false;

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"
  DOCKER_IMAGE_NAME: registry.gitlab.com/onedatashare/transfer-service
  APP_PORT: 8092
  DOCKER_DRIVER: overlay
  APP_NAME: Transfer Service
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

before_script:
  - chmod +x mvnw

#Run maven tests
maven-test:
  image: maven:3-jdk-8
  stage: test
  script:
    - mvn clean test
  artifacts:
    paths:
      - target/

#Build the project
maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/
 
#Run Docker build and push it to the Gitlab Registry
docker-build:
  stage: package
  script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
